sudo: false
language: node_js
node_js: stable
install: yarn
script: yarn test
cache:
  directories:
    - node_modules
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip-cleanup: true
  on:
    tags: true
