name: CI

on:
  push:
    paths:
      - '**.js'
      - 'package.json'
      - 'package-lock.json'

jobs:
  test:
    name: Test with Node.js ${{ matrix.node-version }}, webpack ${{ matrix.webpack-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x, 14.x]
        webpack-version: [4.x, 5.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run code test
        run: npm test
        env:
          WEBPACK_VERSION: ${{ matrix.webpack-version }}
